# Generated by Django 5.2.4 on 2025-08-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at']},
        ),
    ]
