# Generated by Django 5.2.4 on 2025-08-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category'),
        ('api', '0005_review'),
    ]

    operations = [
    ]
