# Generated by Django 5.2.4 on 2025-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_supportchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportchat',
            old_name='Conversation',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
